Repository adityaarakeri/Interview-solved, pull requests merged in 2020-10, with the labels that each got.

#82 #84 - finding odd occurrence with constant space limitation
  Company/find_odd_in_constant_space.py
  test/test_find_odd_in_constant_space.py
Labels: Hactoberfest, hacktoberfest-accepted

#90 Add leetcode 200
  LeetCode/200.py
Labels: hacktoberfest-accepted

#88 Add bin tree height riddle ( #87 )
  TreesAndGraphs/AVL Tree.py
  TreesAndGraphs/Depth-First-Search.py
  TreesAndGraphs/Djikistra.py
  TreesAndGraphs/Red Black Tree.py
  TreesAndGraphs/bin_tree_height.py
  TreesAndGraphs/kruskall.py
  test/test_bin_tree_height.py
  test/test_shuffle_music_playlist.py
Labels: hacktoberfest-accepted

#91 updates
  LeetCode/5079.py
  LeetCode/5080.py
  LeetCode/5205.py
  Microsoft/Average_of_ASCII_values_of_characters_of_a_given_string.py
  Microsoft/Expression_Evaluation.py
  Microsoft/Sum_of_cousins_of_a_given_node_in_a_Binary_Tree.py
  README.md
Labels: hacktoberfest-accepted

#92 Add leetcode 61
  LeetCode/61.py
Labels: Hacktoberfest2020, Hactoberfest, hacktoberfest-accepted

#83 Added a "calculate pi" interview question
  Important/CalculatePi.py
  test/test_CalculatePi.py
Labels: Hacktoberfest2020, Hactoberfest, hacktoberfest-accepted

#98 Add leetcode 94
  LeetCode/94.py
Labels: hacktoberfest-accepted

#76 Added Tortoise_Racing.py
  CodeWars/Tortoise_Racing.py
Labels: hacktoberfest-accepted

#79 Added code for tower of Hanoi in GeeksforGeeks
  GeeksforGeeks/Tower_of_Hanoi.py
Labels: automerge

#72 Added solution of LeetCode #100
  LeetCode/100.py
Labels: automerge

#81 Added code in HackerRank and gfg folder
  GeeksforGeeks/1_N_queens.py
  HackerRank/Equal.py
  HackerRank/Fibonacci_Modified.py
  HackerRank/Sherlock_and_Cost.py
  HackerRank/The_Coin_Change_Problem.py
Labels: automerge

#66 Add files via upload
  HackerRank/Bon-appetit.py
Labels: automerge

#99 GeeksForGeeks interview guide: Adding pythagorean triplet problem and roman to integer conversion #58
  GeeksforGeeks/pythagorean_triplet.py
  GeeksforGeeks/roman_to_integer.py
Labels: automerge

#77 Added sherlock-and-valid-string.py
  HackerRank/sherlock-and-valid-string.py
Labels: automerge
